/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-10-11 at 08:41:11 UTC 
 * Modify at your own risk.
 */

package com.appspot.campus_connect_2015.clubs.model;

/**
 * ProfileMiniForm -- What's shown on the UI
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the clubs. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModelsProfileMiniForm extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String batch;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String branch;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> clubsJoined;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String collegeLocation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String collegeName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> follows;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String isAlumni;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String phone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> tags;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBatch() {
    return batch;
  }

  /**
   * @param batch batch or {@code null} for none
   */
  public ModelsProfileMiniForm setBatch(java.lang.String batch) {
    this.batch = batch;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBranch() {
    return branch;
  }

  /**
   * @param branch branch or {@code null} for none
   */
  public ModelsProfileMiniForm setBranch(java.lang.String branch) {
    this.branch = branch;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getClubsJoined() {
    return clubsJoined;
  }

  /**
   * @param clubsJoined clubsJoined or {@code null} for none
   */
  public ModelsProfileMiniForm setClubsJoined(java.util.List<java.lang.String> clubsJoined) {
    this.clubsJoined = clubsJoined;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCollegeLocation() {
    return collegeLocation;
  }

  /**
   * @param collegeLocation collegeLocation or {@code null} for none
   */
  public ModelsProfileMiniForm setCollegeLocation(java.lang.String collegeLocation) {
    this.collegeLocation = collegeLocation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCollegeName() {
    return collegeName;
  }

  /**
   * @param collegeName collegeName or {@code null} for none
   */
  public ModelsProfileMiniForm setCollegeName(java.lang.String collegeName) {
    this.collegeName = collegeName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public ModelsProfileMiniForm setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getFollows() {
    return follows;
  }

  /**
   * @param follows follows or {@code null} for none
   */
  public ModelsProfileMiniForm setFollows(java.util.List<java.lang.String> follows) {
    this.follows = follows;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIsAlumni() {
    return isAlumni;
  }

  /**
   * @param isAlumni isAlumni or {@code null} for none
   */
  public ModelsProfileMiniForm setIsAlumni(java.lang.String isAlumni) {
    this.isAlumni = isAlumni;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public ModelsProfileMiniForm setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhone() {
    return phone;
  }

  /**
   * @param phone phone or {@code null} for none
   */
  public ModelsProfileMiniForm setPhone(java.lang.String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTags() {
    return tags;
  }

  /**
   * @param tags tags or {@code null} for none
   */
  public ModelsProfileMiniForm setTags(java.util.List<java.lang.String> tags) {
    this.tags = tags;
    return this;
  }

  @Override
  public ModelsProfileMiniForm set(String fieldName, Object value) {
    return (ModelsProfileMiniForm) super.set(fieldName, value);
  }

  @Override
  public ModelsProfileMiniForm clone() {
    return (ModelsProfileMiniForm) super.clone();
  }

}
